### ISSUE TITLE
[client] implement decryption

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#5]
along #1 

either take aes256 from file or recover key from a file with one shamir share per line
Assume that the file provides the correct number of shares needed for recovery

**Comment by haerdib** [comment]
According to #1 this command looks like:

```
ternoa-client decrypt <inputfile> 
# decrypts cyphertext using the aes256 key stored in inputfile.aes256. for debug only

ternoa-client decrypt <inputfile> <keysharesfile>
# reads key shares from second file, shamir-combines the shares into the original assuming the exact number of shares given that is needed
```

however, I interpreted the `inputfile` as the secert (encrypted file) and the `keysharesfile` as the file containin all the keyshares. This approach works, but the client would need to manually get all the keyshares (with the `keyvault get` command). 

We could however change the decrypt command to
```
ternoa-client decrypt <owner> <nftid> <keyvault_urlfile> <encrypted_secret_file>
# iterate through all urls and get keyshares with rpc command <NFTId> <owner> <url> (effective same as 
# implementation ternoa-client keyvault get <NFTId> <owner> <url>)
# use recevied key shares to decrypt secret
```
The nft Id is optional, because the id should be contained in the keyvault_urlfile name.. but since the client knows which nft_id it wants to decode, this extra input would make it easier and less volatile to file name changes.

**Comment by echevrier** [comment]
I implemented according to first interpretation:
`inputfile` is the secret and the `keysharesfile` is the file containig the keyshares. This has to provide the correct number of keyshares needed for recovery
