### ISSUE TITLE
[keyvault] scan ternoa chain and register NFTs in enclave state

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#7]
scan all blocks
maintian NFT registry in atomic pointer to serve the rpc API

Upon all relevant NFT extrinsics, update the local NFT registry (in enclave)
persist NFT registry on disk, together with last blocknumber synched

upon worker restart, consistency must be guaranteed

**Comment by haerdib** [comment]
Documenting some dicusssion points here:
- Reason to save last synced blocknumber even though chain relay already does that: chain relay stores it as well but in different file, so it does not guarantee that both file are on same block number sync state
- we will not use stf, as it would be somewhat of anoverkill (no pallet from ternoa is used..). Instead we will save the atomic pointer snapshot in a file with SgxFile (like [chain relay does it](https://github.com/integritee-network/worker/blob/master/enclave/src/io.rs#L93-L100))

I'm suggesting to use the following struct:
```rust
struct NFTRegistry {
    block_number,
    registry: HashMap<nft_id, nft_data>
    nft_ids: Vec<nftid> // optional, not sure if this is necessary
}
```

**Comment by haerdib** [comment]
There is no reason to read the saved state as long as the enclave is running because we are keeping track of the registry in memory (atomic pointer). The state will only be read upon restart.

@brenzi how can we guarantee consistency? By comparing the loaded state with the state of the chain? 
i.e. comparing the nft_ids vector and then iterate through every entry in the registry hashmap?
